export { default as Home } from './Home'
export { default as Artical } from './Artical'
export { default as ArticalDetail } from './Artical/ArticalDetail'
export { default as Users } from './Users'
export { default as NotFound } from './NotFound'